#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
BIN="$ROOT/build/bin/heresy-pr-response"
CLI="$ROOT/build/bin/heresy360"
SPEC="$ROOT/specimens/enterprise-reliability/github-2026-08-17/incident.tsv"
TMP="$ROOT/build/test-v72"

rm -rf "$TMP"
mkdir -p "$TMP"
trap 'rm -rf "$TMP"' EXIT HUP INT TERM

"$BIN" "$SPEC" > "$TMP/a.txt"
"$BIN" "$SPEC" > "$TMP/b.txt"
cmp "$TMP/a.txt" "$TMP/b.txt"

"$CLI" pr-response > "$TMP/cli.txt"
cmp "$TMP/a.txt" "$TMP/cli.txt"

"$CLI" boot > "$TMP/boot.txt"
grep -F "FORTRAN PUBLIC RELATIONS .. ONLINE" "$TMP/boot.txt"
grep -F "ACTUAL PR RESPONSE ........ NOT CLAIMED" "$TMP/boot.txt"
grep -F "STATUS .................... READY" "$TMP/boot.txt"

grep -F "HERESY/360 v7.2.0 — PUBLIC RELATIONS RESPONSE SIMULATOR" "$TMP/a.txt"
grep -F "ATTRIBUTION: FICTIONAL SATIRE; NOT A GITHUB STATEMENT OR REAL SPOKESPERSON" "$TMP/a.txt"
grep -F "SOURCE_KIND=maintainer_supplied_status_page_snapshot" "$TMP/a.txt"
grep -F "SOURCE_DATE=2026-08-17" "$TMP/a.txt"
grep -F "OBSERVED_WEB_API_ERROR_RATE_PERCENT=20" "$TMP/a.txt"
grep -F "OBSERVED_RAW_DOWNLOAD_ERROR_RATE_PERCENT=50" "$TMP/a.txt"
grep -F "OBSERVED_PACKAGES_STATUS=NORMAL" "$TMP/a.txt"
grep -F "ROOT_CAUSE_INFERRED=0" "$TMP/a.txt"
grep -F "ACTUAL_GITHUB_RESPONSE_CLAIMED=0" "$TMP/a.txt"
grep -F "INTERVIEWER: So a download was, statistically, a coin toss?" "$TMP/a.txt"
grep -F "PUBLIC_RELATIONS: That is a very binary description of a cloud service." "$TMP/a.txt"
grep -F "PUBLIC_RELATIONS: The supplied fields do not establish platform-wide health." "$TMP/a.txt"
grep -F "PUBLIC_RELATIONS: We are reviewing the process that allowed it." "$TMP/a.txt"
grep -F "PUBLIC_RELATIONS: The supplied snapshot does not establish root cause." "$TMP/a.txt"
grep -F "PUBLIC_RELATIONS: No. This exchange is fictional satire generated by Fortran." "$TMP/a.txt"
grep -F "HERESY-E-PR: STATEMENT COMPLETE; NOTHING FURTHER HAS BEEN CLARIFIED." "$TMP/a.txt"

fixture="$TMP/degraded.tsv"
cat > "$fixture" <<'EOF'
SOURCE_KIND	test_fixture
SOURCE_DATE	2026-08-18
WEB_API_ERROR_RATE_PERCENT	20
RAW_DOWNLOAD_ERROR_RATE_PERCENT	50
PACKAGES_STATUS	DEGRADED
EOF
"$BIN" "$fixture" > "$TMP/degraded.txt"
grep -F "OBSERVED_PACKAGES_STATUS=DEGRADED" "$TMP/degraded.txt"
grep -F "PUBLIC_RELATIONS: The supplied fields do not establish platform-wide health." "$TMP/degraded.txt"
grep -F "PUBLIC_RELATIONS: Then we will not make the Packages-normal joke." "$TMP/degraded.txt"
if grep -F "INTERVIEWER: One employee reported for work." "$TMP/degraded.txt" >/dev/null; then
    echo "unsupported Packages-normal joke leaked into v7.2 fixture" >&2
    exit 1
fi
if grep -F "PUBLIC_RELATIONS: Some services were operating normally." "$TMP/degraded.txt" >/dev/null; then
    echo "unsupported normal-service claim leaked into degraded fixture" >&2
    exit 1
fi

zero="$TMP/zero.tsv"
cat > "$zero" <<'EOF'
SOURCE_KIND	test_fixture
SOURCE_DATE	2026-08-18
WEB_API_ERROR_RATE_PERCENT	0
RAW_DOWNLOAD_ERROR_RATE_PERCENT	0
PACKAGES_STATUS	NORMAL
EOF
"$BIN" "$zero" > "$TMP/zero.txt"
grep -F "OBSERVED_RAW_DOWNLOAD_ERROR_RATE_PERCENT=0" "$TMP/zero.txt"
grep -F "INTERVIEWER: The observed raw/archive error rate was zero?" "$TMP/zero.txt"
grep -F "PUBLIC_RELATIONS: For that field in this specimen, yes." "$TMP/zero.txt"
if grep -F "download path was degraded" "$TMP/zero.txt" >/dev/null; then
    echo "zero-error fixture incorrectly described the download path as degraded" >&2
    exit 1
fi
if grep -F "positive observed error rate" "$TMP/zero.txt" >/dev/null; then
    echo "zero-error fixture incorrectly claimed a positive error rate" >&2
    exit 1
fi

duplicate="$TMP/duplicate.tsv"
cp "$SPEC" "$duplicate"
printf 'RAW_DOWNLOAD_ERROR_RATE_PERCENT\t49\n' >> "$duplicate"
if "$BIN" "$duplicate" > "$TMP/duplicate.txt" 2>&1; then
    echo "ambiguous v7.2 specimen unexpectedly accepted" >&2
    exit 1
fi
grep -F "PR_RESPONSE_SPECIMEN_AMBIGUOUS" "$TMP/duplicate.txt"

malformed="$TMP/malformed.tsv"
sed 's/^WEB_API_ERROR_RATE_PERCENT	20$/WEB_API_ERROR_RATE_PERCENT	20	extra/' "$SPEC" > "$malformed"
if "$BIN" "$malformed" > "$TMP/malformed.txt" 2>&1; then
    echo "single malformed required record unexpectedly accepted" >&2
    exit 1
fi
grep -F "PR_RESPONSE_SPECIMEN_AMBIGUOUS" "$TMP/malformed.txt"

range="$TMP/range.tsv"
sed 's/^RAW_DOWNLOAD_ERROR_RATE_PERCENT	50$/RAW_DOWNLOAD_ERROR_RATE_PERCENT	101/' "$SPEC" > "$range"
if "$BIN" "$range" > "$TMP/range.txt" 2>&1; then
    echo "out-of-range v7.2 percentage unexpectedly accepted" >&2
    exit 1
fi
grep -F "PR_RESPONSE_PERCENT_OUT_OF_RANGE" "$TMP/range.txt"

long_value=$(printf '%033d' 101 | tr ' ' '0')
long_percent="$TMP/long-percent.tsv"
sed "s/^RAW_DOWNLOAD_ERROR_RATE_PERCENT	50$/RAW_DOWNLOAD_ERROR_RATE_PERCENT	$long_value/" "$SPEC" > "$long_percent"
if "$BIN" "$long_percent" > "$TMP/long-percent.txt" 2>&1; then
    echo "over-width percentage unexpectedly accepted after fixed-width truncation" >&2
    exit 1
fi
grep -F "PR_RESPONSE_PERCENT_INVALID" "$TMP/long-percent.txt"

if "$BIN" > "$TMP/no-specimen.txt" 2>&1; then
    echo "v7.2 response unexpectedly ran without a specimen" >&2
    exit 1
fi
grep -F "PR_RESPONSE_SPECIMEN_REQUIRED" "$TMP/no-specimen.txt"

echo "HERESY/360 v7.2 tests passed. Public relations has been fact-checked by Fortran."
