C     CLOUD NATIVE API GATEWAY FORTRAN 77 COMPATIBLE IN SPIRIT
      PROGRAM ROUTER
      CHARACTER*12 ROUTES(4)
      INTEGER IROUTE
      DATA ROUTES /'STATUS','DEPLOY','AI','HEALTH'/
      GOTO (100,200,300,400), IROUTE
  100 WRITE(*,*) 'NOMINAL LEGACY OUTLIVED THREE CLOUD STRATEGIES'
      STOP
  200 WRITE(*,*) 'DORIS MOVED CARD TO PRODUCTION TRAY'
      STOP
  300 WRITE(*,*) 'LAMINATED FLOWCHART REPLACED MODEL ACCURACY ROSE'
      STOP
  400 WRITE(*,*) 'HEALTHY SCHEDULED REALITY EXCLUDED'
      STOP
      END
