export const PROGRAM = `10 PRINT "*** COMMODORE BASIC V2 ***"
20 PRINT "38911 BASIC BYTES FREE"
30 PRINT "BOOTING REACT GENERATOR"
40 DATA 72,69,82,69,83,89
50 DATA 82,69,65,67,84
60 DATA 73,78,83,73,68,69
70 DATA 66,65,83,73,67
80 PRINT "READING COMPONENT DATA"
90 PRINT "READY."
100 END`;

const DATA_RE = /^\s*\d+\s+DATA\s+(.+)$/i;
const PRINT_RE = /^\s*\d+\s+PRINT\s+"([^"]*)"\s*$/i;

export function runBasic(program = PROGRAM) {
  const output = [];
  const bytes = [];
  const lines = program.split(/\r?\n/).filter(Boolean).sort((a, b) => parseInt(a) - parseInt(b));

  for (const line of lines) {
    const printed = line.match(PRINT_RE);
    if (printed) output.push(printed[1]);

    const data = line.match(DATA_RE);
    if (data) {
      for (const token of data[1].split(',')) {
        const value = Number(token.trim());
        if (!Number.isInteger(value) || value < 0 || value > 255) throw new Error(`Illegal DATA byte: ${token}`);
        bytes.push(value);
      }
    }
  }

  const words = new TextDecoder().decode(new Uint8Array(bytes)).split(/(?=REACT|INSIDE|BASIC)/).filter(Boolean);
  if (words.join('') !== 'HERESYREACTINSIDEBASIC') throw new Error('Payload identity failure');

  return {
    transcript: output,
    component: {
      eyebrow: 'GENERATED BY COMMODORE BASIC V2',
      title: `${words[1]} ${words[2]} ${words[3]}`,
      body: 'A React component specification crossed a bounded BASIC DATA layer so one button could exist with theological depth.',
      button: 'ACHIEVE SYNERGY'
    }
  };
}
